#spring:
#  cloud:
#    compatibility-verifier:
#      enabled: false
#spring.application.name: sample-spring-modulith
management.tracing.sampling.probability: 1.0
management.endpoints.web.exposure.include: "*"
